### ISSUE TITLE
A question about getting action

### ISSUE THREAD

**Issue by hublan24** [MIT-REALM/gcbfplus#4]
To get action: “action = 2 * self.actor.get_action(params, graph) + self._env.u_ref(graph)” , why do you multiply self.actor.get_action(params, graph) by 2 and why do you use LQR to get self._env.u_ref(graph) instead of PID? Looking forward to your answer and thank you very much!

**Comment by syzhang092218-source** [comment]
Hi! In the environments, we usually define action_lim to be (-1, 1), and the output of self.actor.get_action is also within range (-1, 1) because of the tanh activation function at the last layer. We also clip the output of self._env.u_ref to be within (-1, 1). In this way, if we do not multiply self.actor.get_action by 2, we cannot get a > 0 action if self._env.u_ref outputs -1. For your second question, we feel LQR is much easier to implement than a hand-tuned PID for linear systems.
